version: '3'
services:
  # Database
  db:
    image: mysql:5.7
    volumes: ['./database/mysql:/var/lib/mysql']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: starrec
      MYSQL_DATABASE: starrec
      MYSQL_USER: starrec
      MYSQL_PASSWORD: starrec
    networks:
      - starwork
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - starwork
  # Webserver
  webserver:
    depends_on:
      - db
    image: php:8.0-apache
    ports:
      - '8000:80'
    restart: always
    volumes: ['./code:/var/www/html']
    networks:
      - starwork
networks:
  starwork:
volumes:
  db_data: